/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include <linux/module.h>
#include "clkchk.h"

static const char * const off_pll_names[] = {
	"armca15pll",
	"mmpll",
	"msdcpll",
	"vencpll",
	"tvdpll",
	"vcodecpll",
	"apll1",
	"apll2",
	"lvdspll",
	"msdcpll2",
	NULL
};

static const char * const all_clk_names[] = {
	/* ROOT */
	"clk_null",
	"clk26m",
	"clk32k",
	"clkph_mck_o",
	"usb_syspll_125m",
	"hdmitx_dig_cts",
	/* PLL */
	"armca15pll",
	"armca7pll",
	"mainpll",
	"univpll",
	"mmpll",
	"msdcpll",
	"vencpll",
	"tvdpll",
	"mpll",
	"vcodecpll",
	"apll1",
	"apll2",
	"lvdspll",
	"msdcpll2",
	"ref2usb_tx",
	"armca7pll_754m",
	"armca7pll_502m",
	"main_h546m",
	"main_h364m",
	"main_h218p4m",
	"main_h156m",
	"tvdpll_445p5m",
	"tvdpll_594m",
	"univ_624m",
	"univ_416m",
	"univ_249p6m",
	"univ_178p3m",
	"univ_48m",
	"vcodecpll_370p5",
	/* DIV */
	"clkrtc_ext",
	"clkrtc_int",
	"fpc_ck",
	"hdmitxpll_d2",
	"hdmitxpll_d3",
	"armca7pll_d2",
	"armca7pll_d3",
	"apll1_ck",
	"apll2_ck",
	"dmpll_ck",
	"dmpll_d2",
	"dmpll_d4",
	"dmpll_d8",
	"dmpll_d16",
	"lvdspll_d2",
	"lvdspll_d4",
	"lvdspll_d8",
	"mmpll_ck",
	"mmpll_d2",
	"msdcpll_ck",
	"msdcpll_d2",
	"msdcpll_d4",
	"msdcpll2_ck",
	"msdcpll2_d2",
	"msdcpll2_d4",
	"syspll_d2",
	"syspll1_d2",
	"syspll1_d4",
	"syspll1_d8",
	"syspll1_d16",
	"syspll_d3",
	"syspll2_d2",
	"syspll2_d4",
	"syspll_d5",
	"syspll3_d2",
	"syspll3_d4",
	"syspll_d7",
	"syspll4_d2",
	"syspll4_d4",
	"tvdpll_ck",
	"tvdpll_d2",
	"tvdpll_d4",
	"tvdpll_d8",
	"tvdpll_d16",
	"univpll_d2",
	"univpll1_d2",
	"univpll1_d4",
	"univpll1_d8",
	"univpll_d3",
	"univpll2_d2",
	"univpll2_d4",
	"univpll2_d8",
	"univpll_d5",
	"univpll3_d2",
	"univpll3_d4",
	"univpll3_d8",
	"univpll_d7",
	"univpll_d26",
	"univpll_d52",
	"vcodecpll_ck",
	"vencpll_ck",
	"vencpll_d2",
	"vencpll_d4",
	/* TOP */
	"axi_sel",
	"mem_sel",
	"ddrphycfg_sel",
	"mm_sel",
	"pwm_sel",
	"vdec_sel",
	"venc_sel",
	"mfg_sel",
	"camtg_sel",
	"uart_sel",
	"spi_sel",
	"usb20_sel",
	"usb30_sel",
	"msdc50_0_h_sel",
	"msdc50_0_sel",
	"msdc30_1_sel",
	"msdc30_2_sel",
	"msdc30_3_sel",
	"audio_sel",
	"aud_intbus_sel",
	"pmicspi_sel",
	"scp_sel",
	"atb_sel",
	"venclt_sel",
	"dpi0_sel",
	"irda_sel",
	"cci400_sel",
	"aud_1_sel",
	"aud_2_sel",
	"mem_mfg_in_sel",
	"axi_mfg_in_sel",
	"scam_sel",
	"spinfi_ifr_sel",
	"hdmi_sel",
	"dpilvds_sel",
	"msdc50_2_h_sel",
	"hdcp_sel",
	"hdcp_24m_sel",
	"rtc_sel",
	/* INFRA */
	"infra_pmicwrap",
	"infra_pmicspi",
	"infra_cec",
	"infra_kp",
	"infra_cpum",
	"infra_m4u",
	"infra_l2c_sram",
	"infra_gce",
	"infra_audio",
	"infra_smi",
	"infra_dbgclk",
	/* PERI0 */
	"peri_nfiecc",
	"peri_i2c5",
	"peri_spi0",
	"peri_auxadc",
	"peri_i2c4",
	"peri_i2c3",
	"peri_i2c2",
	"peri_i2c1",
	"peri_i2c0",
	"peri_uart3",
	"peri_uart2",
	"peri_uart1",
	"peri_uart0",
	"peri_irda",
	"peri_nli_arb",
	"peri_msdc30_3",
	"peri_msdc30_2",
	"peri_msdc30_1",
	"peri_msdc30_0",
	"peri_ap_dma",
	"peri_usb1",
	"peri_usb0",
	"peri_pwm",
	"peri_pwm7",
	"peri_pwm6",
	"peri_pwm5",
	"peri_pwm4",
	"peri_pwm3",
	"peri_pwm2",
	"peri_pwm1",
	"peri_therm",
	"peri_nfi",
	/* PERI1 */
	"peri_i2c6",
	"peri_irrx",
	"peri_spi",
	/* IMG */
	"img_fd",
	"img_cam_sv",
	"img_sen_cam",
	"img_sen_tg",
	"img_cam_cam",
	"img_cam_smi",
	"img_larb2_smi",
	/* MM0 */
	"mm_smi_common",
	"mm_smi_larb0",
	"mm_cam_mdp",
	"mm_mdp_rdma0",
	"mm_mdp_rdma1",
	"mm_mdp_rsz0",
	"mm_mdp_rsz1",
	"mm_mdp_rsz2",
	"mm_mdp_tdshp0",
	"mm_mdp_tdshp1",
	"mm_mdp_wdma",
	"mm_mdp_wrot0",
	"mm_mdp_wrot1",
	"mm_fake_eng",
	"mm_mutex_32k",
	"mm_disp_ovl0",
	"mm_disp_ovl1",
	"mm_disp_rdma0",
	"mm_disp_rdma1",
	"mm_disp_rdma2",
	"mm_disp_wdma0",
	"mm_disp_wdma1",
	"mm_disp_color0",
	"mm_disp_color1",
	"mm_disp_aal",
	"mm_disp_gamma",
	"mm_disp_ufoe",
	"mm_disp_split0",
	"mm_disp_split1",
	"mm_disp_merge",
	"mm_disp_od",

	/* MM1 */
	"mm_disp_pwm0mm",
	"mm_disp_pwm026m",
	"mm_disp_pwm1mm",
	"mm_disp_pwm126m",
	"mm_dsi0_engine",
	"mm_dsi0_digital",
	"mm_dsi1_engine",
	"mm_dsi1_digital",
	"mm_dpi_pixel",
	"mm_dpi_engine",
	"mm_dpi1_pixel",
	"mm_dpi1_engine",
	"mm_hdmi_pixel",
	"mm_hdmi_pllck",
	"mm_hdmi_audio",
	"mm_hdmi_spdif",
	"mm_lvds_pixel",
	"mm_lvds_cts",
	"mm_smi_larb4",
	"mm_hdmi_hdcp",
	"mm_hdmi_hdcp24m",
	/* VDEC */
	"vdec_cken",
	"vdec_larb_cken",
	/* VENC */
	"venc_cke0",
	"venc_cke1",
	"venc_cke2",
	"venc_cke3",
	/* VENCLT */
	"venclt_cke0",
	"venclt_cke1",
	/* end */
	NULL
};

static const char * const compatible[] = {"mediatek,mt8173", NULL};

static struct clkchk_cfg cfg = {
	.aee_excp_on_fail = 1,
	.warn_on_fail = 0,
	.compatible = compatible,
	.off_pll_names = off_pll_names,
	.all_clk_names = all_clk_names,
};

static int __init clkchk_platform_init(void)
{
	return clkchk_init(&cfg);
}
subsys_initcall(clkchk_platform_init);
