#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += it6151_nv140fhm_edp_dsi_video.o it6151_i2c.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc




