ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/$(CONFIG_MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(CONFIG_MTK_PLATFORM)/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensorHub/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
obj-y	:=  shf_kernel.o
