#ifndef _CUST_DISO_H_
#define _CUST_DISO_H_

#define MTK_AUXADC_IRQ_SUPPORT

#define MTK_DISCRETE_SWITCH

#if defined(MTK_DISCRETE_SWITCH)
#define AP_AUXADC_DISO_VDC_CHANNEL 0
#define AP_AUXADC_DISO_VUSB_CHANNEL 1
#define R_DISO_DC_PULL_UP 10000
#define R_DISO_DC_PULL_DOWN 1000
#define R_DISO_VBUS_PULL_UP 5100
#define R_DISO_VBUS_PULL_DOWN 1000
#define VDC_MIN_VOLTAGE  BATTERY_VOLT_04_440000_V 
#define VDC_MAX_VOLTAGE BATTERY_VOLT_10_500000_V 
#define VBUS_MIN_VOLTAGE  BATTERY_VOLT_04_440000_V 
#define VBUS_MAX_VOLTAGE BATTERY_VOLT_07_000000_V
#define SWITCH_RISING_TIMING 105
#define SWITCH_FALLING_TIMING 105
#define LOAD_SWITCH_TIMING_MARGIN 30
#define AUXADC_CHANNEL_DEBOUNCE 0x2
#define AUXADC_CHANNEL_DELAY_PERIOD 0x5
#endif
#endif
