# g3dkmd/test/Makefile, used only for built-in kernel

include $(srctree)/drivers/misc/mediatek/gpu/mt8163/mtk_gpu/g3dkmd/builtin.mak

obj-y += tester_core.o
obj-y += tester_non_polling_qload.o
obj-y += tester_non_polling_flushcmd.o
