# Goodix Touchscreen Makefile
# This Makefile is only for tempory compiling use
# Use xxxproject/Makefile-release when release driver
#
# core layer
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX5_NEW)           += goodix_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX5_NEW)           += goodix_ts_core.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX5_NEW)           += goodix_cfg_bin.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX5_UPDATE_NEW)    += goodix_gtx5_update.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX5_TOOLS_NEW)     += goodix_ts_tools.o
