# g3dkmd/debugger/debugfs/Makefile, used only for built-in kernel

include $(srctree)/drivers/misc/mediatek/gpu/mt8163/mtk_gpu/g3dkmd/builtin.mak

obj-y += g3dkmd_prf_kmemory.o
obj-y += g3dkmd_prf_ringbuffer.o
