include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35595_fhd_dsi_cmd_truly_nt50358")
obj-y   +=  nt35595_fhd_dsi_cmd_truly_nt50358.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35595_fhd_dsi_cmd_truly_nt50358_qhd")
obj-y   +=  nt35595_fhd_dsi_cmd_truly_nt50358_qhd.o
endif
