#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

include $(srctree)/drivers/misc/mediatek/video/mt8127/ccflags.mk

obj-$(CONFIG_MTK_FB) += disp_drv.o                  \
		mtkfb_console.o                            	\
		disp_assert_layer.o                       	\
		mtkfb.o                                   	\
		mtkfb_vsync.o								\
		mtkfb_pattern.o                            	\
		disp_debug.o                                    	\
		mtkfb_proc.o								\
		disp_drv_dbi.o								\
		disp_drv_dpi.o								\
		disp_drv_dsi.o								\
		disp_hal.o									\
		disp_intr.o									\
		mtk_mira.o									\
		fbconfig_kdebug.o

obj-$(CONFIG_MTK_OVERLAY_ENGINE_SUPPORT) += ovl_engine/


