# g3dkmd/mmu/Makefile, used only for built-in kernel

include $(srctree)/drivers/misc/mediatek/gpu/mt8163/mtk_gpu/g3dkmd/builtin.mak

obj-y += yl_mmu_bin_internal.o
obj-y += yl_mmu_hw_table.o
obj-y += yl_mmu_iterator.o
obj-y += yl_mmu_kernel_alloc.o
obj-y += yl_mmu_mapper.o
obj-y += yl_mmu_mapper_helper.o
obj-y += yl_mmu_mapper_internal.o
obj-y += yl_mmu_memory_functions.o
obj-y += yl_mmu_rcache.o
obj-y += yl_mmu_section_lookup.o
obj-y += yl_mmu_system_address_translator.o
obj-y += yl_mmu_trunk_internal.o
obj-y += yl_mmu_trunk_metadata_allocator.o
obj-y += yl_mmu_utility.o
