ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat

ccflags-y += -I$(srctree)/drivers/misc/mediatek/videocodec/mt8127/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cameraisp/src/mt8127/inc/

obj-y += mt_spm_mtcmos.o
obj-y += mt-smp.o
obj-y += hotplug.o
obj-y += mt-headsmp.o
obj-y += mt_hotplug.o
obj-y += mt_pm_init.o
obj-y += mt_spm.o
obj-y += mt_dcm.o
obj-y += mt_cpufreq.o
obj-$(CONFIG_ARCH_MT8127) += mt_sleep.o
obj-$(CONFIG_ARCH_MT8127) += mt_spm_sleep.o
obj-y += mt_cpuidle.o
obj-y += mt_ptp.o
obj-y += cpu_dormant-v7.o
obj-y += mt_idle.o
