# g3dkmd/debugger/debugfs/Makefile, used only for built-in kernel

include $(srctree)/drivers/misc/mediatek/gpu/mt8163/mtk_gpu/g3dkmd/builtin.mak

obj-y += g3dkmd_debugfs.o
obj-y += g3dkmd_debugfs_aregs.o
obj-y += g3dkmd_debugfs_task.o
obj-y += g3dkmd_debugfs_fdq.o
obj-y += g3dkmd_debugfs_helper.o
obj-y += g3dkmd_debugfs_log.o
obj-y += g3dkmd_debugfs_profiler.o
